---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "csc-vanity-wallet-generator-deployment"
  namespace: default
spec:
  replicas: 6
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "50%"
      maxSurge: "25%"
  template:
    metadata:
      labels:
        app: "csc-vanity-wallet-generator-app"
        color: green
    spec:
      containers:
        - name: "csc-vanity-wallet-generator"
          image: "whufc4life1/csc-vanity-wallet-generator:b34"
          imagePullPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "csc-vanity-wallet-service-deployment"
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "50%"
      maxSurge: "25%"
  template:
    metadata:
      labels:
        app: "csc-vanity-wallet-service-app"
        color: green
    spec:
      containers:
        - name: "csc-vanity-wallet-service"
          image: "whufc4life1/csc-vanity-wallet-service:b34"
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: csc-vanity-wallet-service
spec:
  ports:
    - port: 8080
  selector:
    app: csc-vanity-wallet-service-app
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: csc-vanity-wallet-db
spec:
  ports:
    - port: 3306
  selector:
    app: csc-vanity-wallet-db
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: csc-vanity-wallet-db
spec:
  selector:
    matchLabels:
      app: csc-vanity-wallet-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: csc-vanity-wallet-db
    spec:
      containers:
        - image: whufc4life1/csc-vanity-wallet-db:b34
          name: csc-vanity-wallet-db
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: MYSQL_DATABASE
              value: wallet-db
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
